spring:
  datasource:
    username: root
    password: 999Iamtinydust
    url: jdbc:mysql://127.0.0.1:3306/jue_tu?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tf.entity
server:
  port: 8080
  servlet:
    context-path: /juetu/api/v1
logging:
  config: classpath:log/logback-spring.xml
fastdep:
  shiro-jwt:
    filter: #shiro过滤规则
      test:
        path: /test/permission
        role: jwt # jwt为需要进行token校验
      front:
        path: /test/login
        role: anon # anon为无需校验
      login:
        path: /sign_in
        role: anon
    secret: "6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52" # jwt秘钥
#    expireTime: 7200000 # token有效期
#    prefix: "Bearer "  # token校验时的前缀
#    signPrefix: "Bearer " # token生成签名的前缀
#    header: "Authorization" # token校验时的header头
#    以下对应为shiro配置参数，无特殊需求无需配置
#    loginUrl:
#    successUrl:
#    unauthorizedUrl:
#    filterChainDefinitions:

