package com.tf.entity;

import java.util.Date;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_id
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_name
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_description
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    private String permissionDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_update_time
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    private Date permissionUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_status
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    private Boolean permissionStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_id
     *
     * @return the value of permission.permission_id
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_id
     *
     * @param permissionId the value for permission.permission_id
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_name
     *
     * @return the value of permission.permission_name
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_name
     *
     * @param permissionName the value for permission.permission_name
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_description
     *
     * @return the value of permission.permission_description
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public String getPermissionDescription() {
        return permissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_description
     *
     * @param permissionDescription the value for permission.permission_description
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription == null ? null : permissionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_update_time
     *
     * @return the value of permission.permission_update_time
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public Date getPermissionUpdateTime() {
        return permissionUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_update_time
     *
     * @param permissionUpdateTime the value for permission.permission_update_time
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public void setPermissionUpdateTime(Date permissionUpdateTime) {
        this.permissionUpdateTime = permissionUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_status
     *
     * @return the value of permission.permission_status
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public Boolean getPermissionStatus() {
        return permissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_status
     *
     * @param permissionStatus the value for permission.permission_status
     *
     * @mbg.generated Wed Jan 22 20:12:57 CST 2020
     */
    public void setPermissionStatus(Boolean permissionStatus) {
        this.permissionStatus = permissionStatus;
    }
}