package com.tf.entity;

import java.util.Date;

public class RoleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role_user_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Integer roleUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.user_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role_user_update_time
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Date roleUserUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role_user_status
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Boolean roleUserStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role_user_id
     *
     * @return the value of role_user.role_user_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Integer getRoleUserId() {
        return roleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role_user_id
     *
     * @param roleUserId the value for role_user.role_user_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRoleUserId(Integer roleUserId) {
        this.roleUserId = roleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role_id
     *
     * @return the value of role_user.role_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role_id
     *
     * @param roleId the value for role_user.role_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.user_id
     *
     * @return the value of role_user.user_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.user_id
     *
     * @param userId the value for role_user.user_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role_user_update_time
     *
     * @return the value of role_user.role_user_update_time
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Date getRoleUserUpdateTime() {
        return roleUserUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role_user_update_time
     *
     * @param roleUserUpdateTime the value for role_user.role_user_update_time
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRoleUserUpdateTime(Date roleUserUpdateTime) {
        this.roleUserUpdateTime = roleUserUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role_user_status
     *
     * @return the value of role_user.role_user_status
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Boolean getRoleUserStatus() {
        return roleUserStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role_user_status
     *
     * @param roleUserStatus the value for role_user.role_user_status
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRoleUserStatus(Boolean roleUserStatus) {
        this.roleUserStatus = roleUserStatus;
    }
}