package com.tf.entity;

import java.util.Date;

public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_permission_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Integer rolePermissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permission_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_permission_update_time
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Date rolePermissionUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_permission_status
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    private Byte rolePermissionStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_permission_id
     *
     * @return the value of role_permission.role_permission_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Integer getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_permission_id
     *
     * @param rolePermissionId the value for role_permission.role_permission_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRolePermissionId(Integer rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_id
     *
     * @return the value of role_permission.role_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_id
     *
     * @param roleId the value for role_permission.role_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permission_id
     *
     * @return the value of role_permission.permission_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permission_id
     *
     * @param permissionId the value for role_permission.permission_id
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_permission_update_time
     *
     * @return the value of role_permission.role_permission_update_time
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Date getRolePermissionUpdateTime() {
        return rolePermissionUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_permission_update_time
     *
     * @param rolePermissionUpdateTime the value for role_permission.role_permission_update_time
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRolePermissionUpdateTime(Date rolePermissionUpdateTime) {
        this.rolePermissionUpdateTime = rolePermissionUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_permission_status
     *
     * @return the value of role_permission.role_permission_status
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public Byte getRolePermissionStatus() {
        return rolePermissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_permission_status
     *
     * @param rolePermissionStatus the value for role_permission.role_permission_status
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    public void setRolePermissionStatus(Byte rolePermissionStatus) {
        this.rolePermissionStatus = rolePermissionStatus;
    }
}