package com.tf.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNull() {
            addCriterion("user_account is null");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNotNull() {
            addCriterion("user_account is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccountEqualTo(String value) {
            addCriterion("user_account =", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotEqualTo(String value) {
            addCriterion("user_account <>", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThan(String value) {
            addCriterion("user_account >", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThanOrEqualTo(String value) {
            addCriterion("user_account >=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThan(String value) {
            addCriterion("user_account <", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThanOrEqualTo(String value) {
            addCriterion("user_account <=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLike(String value) {
            addCriterion("user_account like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotLike(String value) {
            addCriterion("user_account not like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountIn(List<String> values) {
            addCriterion("user_account in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotIn(List<String> values) {
            addCriterion("user_account not in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountBetween(String value1, String value2) {
            addCriterion("user_account between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotBetween(String value1, String value2) {
            addCriterion("user_account not between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNull() {
            addCriterion("user_mobile is null");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNotNull() {
            addCriterion("user_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andUserMobileEqualTo(String value) {
            addCriterion("user_mobile =", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotEqualTo(String value) {
            addCriterion("user_mobile <>", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThan(String value) {
            addCriterion("user_mobile >", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThanOrEqualTo(String value) {
            addCriterion("user_mobile >=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThan(String value) {
            addCriterion("user_mobile <", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThanOrEqualTo(String value) {
            addCriterion("user_mobile <=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLike(String value) {
            addCriterion("user_mobile like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotLike(String value) {
            addCriterion("user_mobile not like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileIn(List<String> values) {
            addCriterion("user_mobile in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotIn(List<String> values) {
            addCriterion("user_mobile not in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileBetween(String value1, String value2) {
            addCriterion("user_mobile between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotBetween(String value1, String value2) {
            addCriterion("user_mobile not between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("user_email is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("user_email is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("user_email =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("user_email <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("user_email >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("user_email >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("user_email <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("user_email <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("user_email like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("user_email not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("user_email in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("user_email not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("user_email between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("user_email not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserJobIsNull() {
            addCriterion("user_job is null");
            return (Criteria) this;
        }

        public Criteria andUserJobIsNotNull() {
            addCriterion("user_job is not null");
            return (Criteria) this;
        }

        public Criteria andUserJobEqualTo(String value) {
            addCriterion("user_job =", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobNotEqualTo(String value) {
            addCriterion("user_job <>", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobGreaterThan(String value) {
            addCriterion("user_job >", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobGreaterThanOrEqualTo(String value) {
            addCriterion("user_job >=", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobLessThan(String value) {
            addCriterion("user_job <", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobLessThanOrEqualTo(String value) {
            addCriterion("user_job <=", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobLike(String value) {
            addCriterion("user_job like", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobNotLike(String value) {
            addCriterion("user_job not like", value, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobIn(List<String> values) {
            addCriterion("user_job in", values, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobNotIn(List<String> values) {
            addCriterion("user_job not in", values, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobBetween(String value1, String value2) {
            addCriterion("user_job between", value1, value2, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserJobNotBetween(String value1, String value2) {
            addCriterion("user_job not between", value1, value2, "userJob");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIsNull() {
            addCriterion("user_company is null");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIsNotNull() {
            addCriterion("user_company is not null");
            return (Criteria) this;
        }

        public Criteria andUserCompanyEqualTo(String value) {
            addCriterion("user_company =", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotEqualTo(String value) {
            addCriterion("user_company <>", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyGreaterThan(String value) {
            addCriterion("user_company >", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("user_company >=", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyLessThan(String value) {
            addCriterion("user_company <", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyLessThanOrEqualTo(String value) {
            addCriterion("user_company <=", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyLike(String value) {
            addCriterion("user_company like", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotLike(String value) {
            addCriterion("user_company not like", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIn(List<String> values) {
            addCriterion("user_company in", values, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotIn(List<String> values) {
            addCriterion("user_company not in", values, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyBetween(String value1, String value2) {
            addCriterion("user_company between", value1, value2, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotBetween(String value1, String value2) {
            addCriterion("user_company not between", value1, value2, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionIsNull() {
            addCriterion("user_description is null");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionIsNotNull() {
            addCriterion("user_description is not null");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionEqualTo(String value) {
            addCriterion("user_description =", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotEqualTo(String value) {
            addCriterion("user_description <>", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionGreaterThan(String value) {
            addCriterion("user_description >", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("user_description >=", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionLessThan(String value) {
            addCriterion("user_description <", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionLessThanOrEqualTo(String value) {
            addCriterion("user_description <=", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionLike(String value) {
            addCriterion("user_description like", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotLike(String value) {
            addCriterion("user_description not like", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionIn(List<String> values) {
            addCriterion("user_description in", values, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotIn(List<String> values) {
            addCriterion("user_description not in", values, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionBetween(String value1, String value2) {
            addCriterion("user_description between", value1, value2, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotBetween(String value1, String value2) {
            addCriterion("user_description not between", value1, value2, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserAvatarIsNull() {
            addCriterion("user_avatar is null");
            return (Criteria) this;
        }

        public Criteria andUserAvatarIsNotNull() {
            addCriterion("user_avatar is not null");
            return (Criteria) this;
        }

        public Criteria andUserAvatarEqualTo(String value) {
            addCriterion("user_avatar =", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarNotEqualTo(String value) {
            addCriterion("user_avatar <>", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarGreaterThan(String value) {
            addCriterion("user_avatar >", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("user_avatar >=", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarLessThan(String value) {
            addCriterion("user_avatar <", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarLessThanOrEqualTo(String value) {
            addCriterion("user_avatar <=", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarLike(String value) {
            addCriterion("user_avatar like", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarNotLike(String value) {
            addCriterion("user_avatar not like", value, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarIn(List<String> values) {
            addCriterion("user_avatar in", values, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarNotIn(List<String> values) {
            addCriterion("user_avatar not in", values, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarBetween(String value1, String value2) {
            addCriterion("user_avatar between", value1, value2, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andUserAvatarNotBetween(String value1, String value2) {
            addCriterion("user_avatar not between", value1, value2, "userAvatar");
            return (Criteria) this;
        }

        public Criteria andJuetuValueIsNull() {
            addCriterion("juetu_value is null");
            return (Criteria) this;
        }

        public Criteria andJuetuValueIsNotNull() {
            addCriterion("juetu_value is not null");
            return (Criteria) this;
        }

        public Criteria andJuetuValueEqualTo(Integer value) {
            addCriterion("juetu_value =", value, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueNotEqualTo(Integer value) {
            addCriterion("juetu_value <>", value, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueGreaterThan(Integer value) {
            addCriterion("juetu_value >", value, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("juetu_value >=", value, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueLessThan(Integer value) {
            addCriterion("juetu_value <", value, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueLessThanOrEqualTo(Integer value) {
            addCriterion("juetu_value <=", value, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueIn(List<Integer> values) {
            addCriterion("juetu_value in", values, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueNotIn(List<Integer> values) {
            addCriterion("juetu_value not in", values, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueBetween(Integer value1, Integer value2) {
            addCriterion("juetu_value between", value1, value2, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andJuetuValueNotBetween(Integer value1, Integer value2) {
            addCriterion("juetu_value not between", value1, value2, "juetuValue");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsIsNull() {
            addCriterion("user_blog_views is null");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsIsNotNull() {
            addCriterion("user_blog_views is not null");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsEqualTo(Integer value) {
            addCriterion("user_blog_views =", value, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsNotEqualTo(Integer value) {
            addCriterion("user_blog_views <>", value, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsGreaterThan(Integer value) {
            addCriterion("user_blog_views >", value, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_blog_views >=", value, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsLessThan(Integer value) {
            addCriterion("user_blog_views <", value, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsLessThanOrEqualTo(Integer value) {
            addCriterion("user_blog_views <=", value, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsIn(List<Integer> values) {
            addCriterion("user_blog_views in", values, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsNotIn(List<Integer> values) {
            addCriterion("user_blog_views not in", values, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsBetween(Integer value1, Integer value2) {
            addCriterion("user_blog_views between", value1, value2, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogViewsNotBetween(Integer value1, Integer value2) {
            addCriterion("user_blog_views not between", value1, value2, "userBlogViews");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsIsNull() {
            addCriterion("user_blog_thumbs is null");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsIsNotNull() {
            addCriterion("user_blog_thumbs is not null");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsEqualTo(Integer value) {
            addCriterion("user_blog_thumbs =", value, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsNotEqualTo(Integer value) {
            addCriterion("user_blog_thumbs <>", value, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsGreaterThan(Integer value) {
            addCriterion("user_blog_thumbs >", value, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_blog_thumbs >=", value, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsLessThan(Integer value) {
            addCriterion("user_blog_thumbs <", value, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsLessThanOrEqualTo(Integer value) {
            addCriterion("user_blog_thumbs <=", value, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsIn(List<Integer> values) {
            addCriterion("user_blog_thumbs in", values, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsNotIn(List<Integer> values) {
            addCriterion("user_blog_thumbs not in", values, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsBetween(Integer value1, Integer value2) {
            addCriterion("user_blog_thumbs between", value1, value2, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserBlogThumbsNotBetween(Integer value1, Integer value2) {
            addCriterion("user_blog_thumbs not between", value1, value2, "userBlogThumbs");
            return (Criteria) this;
        }

        public Criteria andUserHomeIsNull() {
            addCriterion("user_home is null");
            return (Criteria) this;
        }

        public Criteria andUserHomeIsNotNull() {
            addCriterion("user_home is not null");
            return (Criteria) this;
        }

        public Criteria andUserHomeEqualTo(String value) {
            addCriterion("user_home =", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeNotEqualTo(String value) {
            addCriterion("user_home <>", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeGreaterThan(String value) {
            addCriterion("user_home >", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeGreaterThanOrEqualTo(String value) {
            addCriterion("user_home >=", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeLessThan(String value) {
            addCriterion("user_home <", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeLessThanOrEqualTo(String value) {
            addCriterion("user_home <=", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeLike(String value) {
            addCriterion("user_home like", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeNotLike(String value) {
            addCriterion("user_home not like", value, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeIn(List<String> values) {
            addCriterion("user_home in", values, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeNotIn(List<String> values) {
            addCriterion("user_home not in", values, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeBetween(String value1, String value2) {
            addCriterion("user_home between", value1, value2, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserHomeNotBetween(String value1, String value2) {
            addCriterion("user_home not between", value1, value2, "userHome");
            return (Criteria) this;
        }

        public Criteria andUserWeiboIsNull() {
            addCriterion("user_weibo is null");
            return (Criteria) this;
        }

        public Criteria andUserWeiboIsNotNull() {
            addCriterion("user_weibo is not null");
            return (Criteria) this;
        }

        public Criteria andUserWeiboEqualTo(String value) {
            addCriterion("user_weibo =", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboNotEqualTo(String value) {
            addCriterion("user_weibo <>", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboGreaterThan(String value) {
            addCriterion("user_weibo >", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboGreaterThanOrEqualTo(String value) {
            addCriterion("user_weibo >=", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboLessThan(String value) {
            addCriterion("user_weibo <", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboLessThanOrEqualTo(String value) {
            addCriterion("user_weibo <=", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboLike(String value) {
            addCriterion("user_weibo like", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboNotLike(String value) {
            addCriterion("user_weibo not like", value, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboIn(List<String> values) {
            addCriterion("user_weibo in", values, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboNotIn(List<String> values) {
            addCriterion("user_weibo not in", values, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboBetween(String value1, String value2) {
            addCriterion("user_weibo between", value1, value2, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserWeiboNotBetween(String value1, String value2) {
            addCriterion("user_weibo not between", value1, value2, "userWeibo");
            return (Criteria) this;
        }

        public Criteria andUserGithubIsNull() {
            addCriterion("user_github is null");
            return (Criteria) this;
        }

        public Criteria andUserGithubIsNotNull() {
            addCriterion("user_github is not null");
            return (Criteria) this;
        }

        public Criteria andUserGithubEqualTo(String value) {
            addCriterion("user_github =", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubNotEqualTo(String value) {
            addCriterion("user_github <>", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubGreaterThan(String value) {
            addCriterion("user_github >", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubGreaterThanOrEqualTo(String value) {
            addCriterion("user_github >=", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubLessThan(String value) {
            addCriterion("user_github <", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubLessThanOrEqualTo(String value) {
            addCriterion("user_github <=", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubLike(String value) {
            addCriterion("user_github like", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubNotLike(String value) {
            addCriterion("user_github not like", value, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubIn(List<String> values) {
            addCriterion("user_github in", values, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubNotIn(List<String> values) {
            addCriterion("user_github not in", values, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubBetween(String value1, String value2) {
            addCriterion("user_github between", value1, value2, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserGithubNotBetween(String value1, String value2) {
            addCriterion("user_github not between", value1, value2, "userGithub");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumIsNull() {
            addCriterion("user_blog_num is null");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumIsNotNull() {
            addCriterion("user_blog_num is not null");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumEqualTo(Integer value) {
            addCriterion("user_blog_num =", value, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumNotEqualTo(Integer value) {
            addCriterion("user_blog_num <>", value, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumGreaterThan(Integer value) {
            addCriterion("user_blog_num >", value, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_blog_num >=", value, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumLessThan(Integer value) {
            addCriterion("user_blog_num <", value, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumLessThanOrEqualTo(Integer value) {
            addCriterion("user_blog_num <=", value, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumIn(List<Integer> values) {
            addCriterion("user_blog_num in", values, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumNotIn(List<Integer> values) {
            addCriterion("user_blog_num not in", values, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumBetween(Integer value1, Integer value2) {
            addCriterion("user_blog_num between", value1, value2, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBlogNumNotBetween(Integer value1, Integer value2) {
            addCriterion("user_blog_num not between", value1, value2, "userBlogNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumIsNull() {
            addCriterion("user_book_num is null");
            return (Criteria) this;
        }

        public Criteria andUserBookNumIsNotNull() {
            addCriterion("user_book_num is not null");
            return (Criteria) this;
        }

        public Criteria andUserBookNumEqualTo(Integer value) {
            addCriterion("user_book_num =", value, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumNotEqualTo(Integer value) {
            addCriterion("user_book_num <>", value, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumGreaterThan(Integer value) {
            addCriterion("user_book_num >", value, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_book_num >=", value, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumLessThan(Integer value) {
            addCriterion("user_book_num <", value, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumLessThanOrEqualTo(Integer value) {
            addCriterion("user_book_num <=", value, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumIn(List<Integer> values) {
            addCriterion("user_book_num in", values, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumNotIn(List<Integer> values) {
            addCriterion("user_book_num not in", values, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumBetween(Integer value1, Integer value2) {
            addCriterion("user_book_num between", value1, value2, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserBookNumNotBetween(Integer value1, Integer value2) {
            addCriterion("user_book_num not between", value1, value2, "userBookNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumIsNull() {
            addCriterion("user_treehole_num is null");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumIsNotNull() {
            addCriterion("user_treehole_num is not null");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumEqualTo(Integer value) {
            addCriterion("user_treehole_num =", value, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumNotEqualTo(Integer value) {
            addCriterion("user_treehole_num <>", value, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumGreaterThan(Integer value) {
            addCriterion("user_treehole_num >", value, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_treehole_num >=", value, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumLessThan(Integer value) {
            addCriterion("user_treehole_num <", value, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumLessThanOrEqualTo(Integer value) {
            addCriterion("user_treehole_num <=", value, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumIn(List<Integer> values) {
            addCriterion("user_treehole_num in", values, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumNotIn(List<Integer> values) {
            addCriterion("user_treehole_num not in", values, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumBetween(Integer value1, Integer value2) {
            addCriterion("user_treehole_num between", value1, value2, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserTreeholeNumNotBetween(Integer value1, Integer value2) {
            addCriterion("user_treehole_num not between", value1, value2, "userTreeholeNum");
            return (Criteria) this;
        }

        public Criteria andUserSaltIsNull() {
            addCriterion("user_salt is null");
            return (Criteria) this;
        }

        public Criteria andUserSaltIsNotNull() {
            addCriterion("user_salt is not null");
            return (Criteria) this;
        }

        public Criteria andUserSaltEqualTo(String value) {
            addCriterion("user_salt =", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotEqualTo(String value) {
            addCriterion("user_salt <>", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltGreaterThan(String value) {
            addCriterion("user_salt >", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltGreaterThanOrEqualTo(String value) {
            addCriterion("user_salt >=", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLessThan(String value) {
            addCriterion("user_salt <", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLessThanOrEqualTo(String value) {
            addCriterion("user_salt <=", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLike(String value) {
            addCriterion("user_salt like", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotLike(String value) {
            addCriterion("user_salt not like", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltIn(List<String> values) {
            addCriterion("user_salt in", values, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotIn(List<String> values) {
            addCriterion("user_salt not in", values, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltBetween(String value1, String value2) {
            addCriterion("user_salt between", value1, value2, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotBetween(String value1, String value2) {
            addCriterion("user_salt not between", value1, value2, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNull() {
            addCriterion("user_status is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNotNull() {
            addCriterion("user_status is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusEqualTo(Byte value) {
            addCriterion("user_status =", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotEqualTo(Byte value) {
            addCriterion("user_status <>", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThan(Byte value) {
            addCriterion("user_status >", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_status >=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThan(Byte value) {
            addCriterion("user_status <", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThanOrEqualTo(Byte value) {
            addCriterion("user_status <=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusIn(List<Byte> values) {
            addCriterion("user_status in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotIn(List<Byte> values) {
            addCriterion("user_status not in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusBetween(Byte value1, Byte value2) {
            addCriterion("user_status between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("user_status not between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIsNull() {
            addCriterion("user_create_time is null");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIsNotNull() {
            addCriterion("user_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeEqualTo(Date value) {
            addCriterion("user_create_time =", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotEqualTo(Date value) {
            addCriterion("user_create_time <>", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeGreaterThan(Date value) {
            addCriterion("user_create_time >", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_create_time >=", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeLessThan(Date value) {
            addCriterion("user_create_time <", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_create_time <=", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIn(List<Date> values) {
            addCriterion("user_create_time in", values, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotIn(List<Date> values) {
            addCriterion("user_create_time not in", values, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeBetween(Date value1, Date value2) {
            addCriterion("user_create_time between", value1, value2, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_create_time not between", value1, value2, "userCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jue_tu..user
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 22 20:27:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jue_tu..user
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}