package com.tf.entity;

import org.dozer.Mapping;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_id
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_account
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_password
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_mobile
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private String userMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_email
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_name
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_job
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("job")
    private String userJob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_company
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("company")
    private String userCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_description
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("description")
    private String userDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_avatar
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("avatar")
    private String userAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.juetu_value
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private Integer juetuValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_blog_views
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("blogViews")
    private Integer userBlogViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_blog_thumbs
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("blogThumbs")
    private Integer userBlogThumbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_home
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("home")
    private String userHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_weibo
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("weibo")
    private String userWeibo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_github
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("github")
    private String userGithub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_blog_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("blogNum")
    private Integer userBlogNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_book_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("bookNum")
    private Integer userBookNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_treehole_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("treeholeNum")
    private Integer userTreeholeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_salt
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private String userSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_status
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    private Byte userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jue_tu..user.user_create_time
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    @Mapping("createTime")
    private Date userCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_id
     *
     * @return the value of jue_tu..user.user_id
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_id
     *
     * @param userId the value for jue_tu..user.user_id
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_account
     *
     * @return the value of jue_tu..user.user_account
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_account
     *
     * @param userAccount the value for jue_tu..user.user_account
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_password
     *
     * @return the value of jue_tu..user.user_password
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_password
     *
     * @param userPassword the value for jue_tu..user.user_password
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_mobile
     *
     * @return the value of jue_tu..user.user_mobile
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_mobile
     *
     * @param userMobile the value for jue_tu..user.user_mobile
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_email
     *
     * @return the value of jue_tu..user.user_email
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_email
     *
     * @param userEmail the value for jue_tu..user.user_email
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_name
     *
     * @return the value of jue_tu..user.user_name
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_name
     *
     * @param userName the value for jue_tu..user.user_name
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_job
     *
     * @return the value of jue_tu..user.user_job
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserJob() {
        return userJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_job
     *
     * @param userJob the value for jue_tu..user.user_job
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserJob(String userJob) {
        this.userJob = userJob == null ? null : userJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_company
     *
     * @return the value of jue_tu..user.user_company
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserCompany() {
        return userCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_company
     *
     * @param userCompany the value for jue_tu..user.user_company
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserCompany(String userCompany) {
        this.userCompany = userCompany == null ? null : userCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_description
     *
     * @return the value of jue_tu..user.user_description
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_description
     *
     * @param userDescription the value for jue_tu..user.user_description
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription == null ? null : userDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_avatar
     *
     * @return the value of jue_tu..user.user_avatar
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_avatar
     *
     * @param userAvatar the value for jue_tu..user.user_avatar
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar == null ? null : userAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.juetu_value
     *
     * @return the value of jue_tu..user.juetu_value
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Integer getJuetuValue() {
        return juetuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.juetu_value
     *
     * @param juetuValue the value for jue_tu..user.juetu_value
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setJuetuValue(Integer juetuValue) {
        this.juetuValue = juetuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_blog_views
     *
     * @return the value of jue_tu..user.user_blog_views
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Integer getUserBlogViews() {
        return userBlogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_blog_views
     *
     * @param userBlogViews the value for jue_tu..user.user_blog_views
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserBlogViews(Integer userBlogViews) {
        this.userBlogViews = userBlogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_blog_thumbs
     *
     * @return the value of jue_tu..user.user_blog_thumbs
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Integer getUserBlogThumbs() {
        return userBlogThumbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_blog_thumbs
     *
     * @param userBlogThumbs the value for jue_tu..user.user_blog_thumbs
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserBlogThumbs(Integer userBlogThumbs) {
        this.userBlogThumbs = userBlogThumbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_home
     *
     * @return the value of jue_tu..user.user_home
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserHome() {
        return userHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_home
     *
     * @param userHome the value for jue_tu..user.user_home
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserHome(String userHome) {
        this.userHome = userHome == null ? null : userHome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_weibo
     *
     * @return the value of jue_tu..user.user_weibo
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserWeibo() {
        return userWeibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_weibo
     *
     * @param userWeibo the value for jue_tu..user.user_weibo
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserWeibo(String userWeibo) {
        this.userWeibo = userWeibo == null ? null : userWeibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_github
     *
     * @return the value of jue_tu..user.user_github
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserGithub() {
        return userGithub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_github
     *
     * @param userGithub the value for jue_tu..user.user_github
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserGithub(String userGithub) {
        this.userGithub = userGithub == null ? null : userGithub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_blog_num
     *
     * @return the value of jue_tu..user.user_blog_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Integer getUserBlogNum() {
        return userBlogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_blog_num
     *
     * @param userBlogNum the value for jue_tu..user.user_blog_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserBlogNum(Integer userBlogNum) {
        this.userBlogNum = userBlogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_book_num
     *
     * @return the value of jue_tu..user.user_book_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Integer getUserBookNum() {
        return userBookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_book_num
     *
     * @param userBookNum the value for jue_tu..user.user_book_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserBookNum(Integer userBookNum) {
        this.userBookNum = userBookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_treehole_num
     *
     * @return the value of jue_tu..user.user_treehole_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Integer getUserTreeholeNum() {
        return userTreeholeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_treehole_num
     *
     * @param userTreeholeNum the value for jue_tu..user.user_treehole_num
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserTreeholeNum(Integer userTreeholeNum) {
        this.userTreeholeNum = userTreeholeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_salt
     *
     * @return the value of jue_tu..user.user_salt
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public String getUserSalt() {
        return userSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_salt
     *
     * @param userSalt the value for jue_tu..user.user_salt
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserSalt(String userSalt) {
        this.userSalt = userSalt == null ? null : userSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_status
     *
     * @return the value of jue_tu..user.user_status
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_status
     *
     * @param userStatus the value for jue_tu..user.user_status
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jue_tu..user.user_create_time
     *
     * @return the value of jue_tu..user.user_create_time
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jue_tu..user.user_create_time
     *
     * @param userCreateTime the value for jue_tu..user.user_create_time
     *
     * @mbg.generated Wed Jan 22 20:27:21 CST 2020
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }
}