package com.tf.dao;

import com.tf.entity.RoleUser;
import com.tf.entity.RoleUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    long countByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int deleteByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int deleteByPrimaryKey(Integer roleUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int insertSelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    List<RoleUser> selectByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    RoleUser selectByPrimaryKey(Integer roleUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleUser record, @Param("example") RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int updateByExample(@Param("record") RoleUser record, @Param("example") RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int updateByPrimaryKeySelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Wed Jan 22 18:46:44 CST 2020
     */
    int updateByPrimaryKey(RoleUser record);
}